import './modalCall'
import './modalChat'
import './modalCloserBtn'
import './modalCloser'
import './menu'
import './menuCloserBtn'
import './menuCloser'
import './swiper-brands'
import './swiper-gadgets'
import './swiper-table'
import './historyBtn'
import './brandsBtn'
import './gadgetsBtn'
import '../scss/style.scss'

